#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

echo -e "${GREEN}Deployment completed successfully!${NC}"
echo ""

# Get the outputs from the deployment
echo -e "${YELLOW}Creating .env file for event generator...${NC}"

# Get outputs from azd and parse JSON
outputs=$(azd env get-values --output json)

# Extract values using jq (more robust) or grep/sed fallback
if command -v jq &> /dev/null; then
    eventHubNamespaceFqdn=$(echo "$outputs" | jq -r '.eventHubNamespaceFqdn')
    eventHubName=$(echo "$outputs" | jq -r '.eventHubName')
else
    # Fallback using grep and sed if jq is not available
    eventHubNamespaceFqdn=$(echo "$outputs" | grep '"eventHubNamespaceFqdn"' | sed 's/.*"eventHubNamespaceFqdn"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
    eventHubName=$(echo "$outputs" | grep '"eventHubName"' | sed 's/.*"eventHubName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# Create the .env file for the event generator
envPath="./event-generator/.env"

cat > "$envPath" << EOF
# Event Generator Configuration - Generated by azd postprovision
# Uses DefaultAzureCredential for authentication (Azure CLI locally)

EVENT_HUB_NAMESPACE=$eventHubNamespaceFqdn
EVENT_HUB_NAME=$eventHubName

# Generator settings
POLL_INTERVAL=1

# Note: When running locally, authenticate with Azure CLI: az login
EOF

echo -e "${GREEN}✅ Created $envPath${NC}"
echo ""
echo -e "${CYAN}Event generator is configured with:${NC}"
echo -e "${WHITE}  Event Hub Namespace: $eventHubNamespaceFqdn${NC}"
echo -e "${WHITE}  Event Hub Name: $eventHubName${NC}"
echo -e "${WHITE}  Authentication: DefaultAzureCredential${NC}"
echo ""
echo -e "${YELLOW}To run the event generator:${NC}"
echo -e "${WHITE}  cd event-generator${NC}"
echo -e "${WHITE}  pip install -e .${NC}"
echo -e "${WHITE}  python -m vehicle_generator.cli feed --agency 'demo-transit'${NC}"
echo ""
echo -e "${YELLOW}Note: For local development, ensure you're logged in with Azure CLI:${NC}"
echo -e "${WHITE}  az login${NC}"